/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros_rosjava_tutorial_native_node_LocalizationNativeNode */

#ifndef _Included_org_ros_rosjava_tutorial_native_node_LocalizationNativeNode
#define _Included_org_ros_rosjava_tutorial_native_node_LocalizationNativeNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ros_rosjava_tutorial_native_node_LocalizationNativeNode
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_LocalizationNativeNode_execute
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_LocalizationNativeNode
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_LocalizationNativeNode_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
